version: 2

models:
  - name: stg_sales__customers
    description: "This table gives us details about Local Bike customers"
    columns:
      - name: customer_id
        description: "This is the  primary key, unique identifier for the  customers."
        tests:
          - unique
          - not_null

  - name: stg_sales__staffs
    description: "This table contains details about Local Bike staff members."

    columns:
      - name: staff_id
        description: "Primary key. Unique identifier for each staff member."
        tests:
          - unique
          - not_null

      - name: store_id
        description: "Foreign key linking each staff member to their store."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_sales__staffs
              arguments:
                to: ref('stg_sales__stores')
                field: store_id

      - name: manager_id
        description: "Self-referencing foreign key linking each staff member to their manager."
        tests:
          - relationships:
              name: manager_id_foreign_key_in_stg_sales__staffs
              arguments:
                to: ref('stg_sales__staffs')
                field: staff_id


  - name: stg_sales__stores
    description: "This model gives us details about the stores"
    columns: 
      - name: store_id
        description: "This is the  primary key, unique identifier for the  stores."
        tests:
          - unique
          - not_null

  - name: stg_sales__orders
    description: "This model contains details about orders placed by customers, including the status of each order."
    columns:
      - name: order_id
        description: "This is the primary key, unique identifier for each order"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key linking each order  to their customer."
        tests:
          - relationships:
              name: customer_id_foreign_key_in_stg_sales__orders
              arguments:
                to: ref('stg_sales__customers')
                field: customer_id

      - name: store_id
        description: "Foreign key linking each order to the store they ordered from."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_sales_orders
              arguments: 
                to: ref('stg_sales__store_id')
                field: store_id

      - name: staff_id
        description: "Foreign key linking each order to the staff member in charge of the order"
        tests:
          - relationships:
              name: staff_id_foreign_key_in_stg_sales__orders
              arguments: 
                to: ref('stg_sales__staffs')
                field: staff_id
        
      - name: order_status
        description: "The current status of the order."
        tests:
          - accepted_values:
              name: accepted_values_order_status
              arguments: 
                values: [1,2,3,4]
                quote: false

  - name: stg_sales__order_items
    description: "This model contains information about each item included in an order, including its price, quantity, and the discount applied."
    columns:
      - name: order_item_id
        description: "Surrogate key generated from order_id, item_id and product_id."
        tests:
          - not_null
          - unique
          
      - name: order_id
        description: "Foreign key linking each order item to the corresponding order"
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_sales__order_item
              arguments: 
                to: ref('stg_sales__orders')
                field: order_id

      - name: product_id
        description: "Foreign key linking each order item to the corresponding product"
        tests:
          - relationships:
              name: product_id_foreign_key_in_stg_sales__order_items
              arguments: 
                to: ref('stg_sales__products')
                field: product_id

      - name: total_order_item_amount
        description: "The total amount for this order item, calculated as (price * quantity) - discount."